Create .travis.yml
snyk-labs/snyk-cicd-integration-examples pull request #13
Opened 2020-07-23 13:22 UTC by snyk-schmidtty

TravisCI example

2020-08-11 07:27 UTC, sameer4aug commented
#10

2020-09-21 20:10 UTC, maxjeffos requested changes
@snyk-schmidtty can you add this file to a folder like the other examples and also include add a comment or something indicating how you expect the authentication to work? Also, is there a reason you don't have `snyk test`?

2020-09-21 20:11 UTC, maxjeffos commented on .travis.yml
> +    - snyk monitor --all-projects
A note about how snyk is authenticated in this example would be good.

2020-09-21 20:11 UTC, maxjeffos commented on .travis.yml
> +    - snyk monitor --all-projects
Why no `snyk test`?

2020-09-22 16:51 UTC, snyk-schmidtty commented on .travis.yml
> +    - snyk monitor --all-projects
Updated.

2020-09-22 16:52 UTC, snyk-schmidtty commented on .travis.yml
> +    - snyk monitor --all-projects
Updated with Snyk auth and moved to TravisCI folder.

2020-09-22 17:11 UTC, closed without merging

2020-09-22 17:11 UTC, snyk-schmidtty commented
Duplicate.