Create Jenkinsfile-npm-install-with-snyk-filter.groovy
snyk-labs/snyk-cicd-integration-examples pull request #60
Opened 2022-07-06 14:00 UTC by dani-kline

Added Jenkinsfile example using plugin & snyk-filter

2022-07-06 17:47 UTC, scotte-snyk commented
nit: would be good to make the commit message just the "Add Jenkinsfile example using plugin & snyk filter" so its a little more clear on the commit, rather than the auto generated "Create <file>" entry which isnt so descriptive/human readable...

2022-07-06 17:47 UTC, scotte-snyk approved these changes

2022-07-08 14:00 UTC, huytquach-snyk commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +               echo 'Initialize & Cleanup Workspace'
We can remove the cleanup stage. We could add a cleanup after build but its not a big deal.

2022-07-11 15:06 UTC, dani-kline commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> -    stages {
Good catch on the typo, thank you!

2022-07-11 15:47 UTC, sebsnyk requested changes
Thank you @dani-kline for this awesome contribution & your patience. 
Nice to see `snyk-filter` getting spotlight. :)

2022-07-11 15:47 UTC, sebsnyk commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +                sh 'ls -la'
no need for this one

2022-07-11 15:47 UTC, sebsnyk commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +                // Clone the repo that is going to be built
please remove the line as the next one is obvious

2022-07-11 15:47 UTC, sebsnyk commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +            // Run snyk test to check for vulnerabilities and fail the build if any are found
Remove all comments unless they are needed for clarity. Because the plugin documentation is linked above, it is not needed to document every parameter again.

2022-07-11 15:47 UTC, sebsnyk commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +                sh 'snyk-filter -i vuln.json -f snyk-filter/exploitable_cvss_9.yml'
I suggest to remove the comment on snyk-filter here and explain in a oneliner on top of the `snykSecurity` step what we achieve.

`snyk-filter` requires a file `exploitable_cvss_9.yml`, can we document it in the local README.md file (show the contents for reference).

Please rename `vuln.json` to `all-vulnerabilities.json` for self-describing name.

2022-07-11 15:47 UTC, sebsnyk commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +    // Install the Jenkins tools you need for your project / environment
remove the comments here & on line 10 as they seem to come from another template

2022-07-26 17:51 UTC, dani-kline commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +            // Run snyk test to check for vulnerabilities and fail the build if any are found
I don't see monitorOnBuild in the README for the plugin in our repo for it, nor in the Jenkins docs for our plugin, but it is listed [here](https://www.jenkins.io/doc/pipeline/steps/snyk-security-scanner/). I'll check this week to verify that it works in the most recent version of the plugin/jenkins and if that is the case--should I leave the comment for monitorProjectOnBuild as monitor is the default and unsupported by snyk-filter?

2022-07-26 18:02 UTC, dani-kline commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +                sh 'snyk-filter -i vuln.json -f snyk-filter/exploitable_cvss_9.yml'
(apologies for the notifications, I'm adding this here so I know what's left for me to do)
- [ ] Add filter documentation & example to README

2022-07-27 14:20 UTC, sebsnyk commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +                sh 'ls -la'
I think this refers to the `ls -la` sh command, which is not needed to clone the repo. You can also remove the `//` comment.

2022-07-27 14:50 UTC, sebsnyk commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +            // Run snyk test to check for vulnerabilities and fail the build if any are found
Yes, keep the comment on `monitorProjectOnBuild`. I had no idea we support this option.. (raised with RR). Agree with `failOnIssues` as well. Document what is necessary, indeed. Thank you!

2022-07-27 14:52 UTC, sebsnyk commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +        stage('Build') {
Can we split this into a `Install Snyk` stage and a `Build` stage, whereas the `Build` stage is commented out. The `npm install` command can be combined (browserify line can be removed). Idea is to be very clear where the Snyk world starts/ends and where the customer should add lines to build the App.

2022-07-27 20:23 UTC, dani-kline commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +            // Run snyk test to check for vulnerabilities and fail the build if any are found
Thank you! 
I tested it without monitorProjectOnBuild: false, and it does run the test & run snyk-filter, but it doesn't monitor & provides an error message `The following option combination is not currently supported: monitor + json-file-output
Failed to monitor project. (Exit Code: 2)`. Knowing this, is it worth keeping the monitorProjectOnBuild line?

2022-08-02 11:57 UTC, sebsnyk reviewed
last 3 tiny bits, then we are done. Great work!

2022-08-02 11:57 UTC, sebsnyk commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +                sh 'npm install -g node-jq snyk-filter'
nit: instead of `-g`, please use `--location=global` - new-style npm

2022-08-02 11:57 UTC, sebsnyk commented on Jenkins/Jenkinsfile-npm-install-with-snyk-filter.groovy
> +                sh 'snyk-filter -i vuln.json -f snyk-filter/exploitable_cvss_9.yml'
please name `vuln.json` to `all-vulnerabilities.json` on this line

2022-08-02 11:57 UTC, sebsnyk commented on Jenkins/exploitable_cvss_9.yml
> +# This is an example of a filter to be used with snyk-filter in Jenkins example. Please see the snyk-filter repo for more information and formatting guidelines.
please link to the snyk-filter repo in the comment

2022-08-04 08:06 UTC, sebsnyk approved these changes
Really good!

2022-08-04 09:07 UTC, merged