Adding GitHub action for Windows .NET Snyk CLI
snyk-labs/snyk-cicd-integration-examples pull request #72
Opened 2023-02-09 13:51 UTC by harrykimpel

Signed-off-by: Harry Kimpel <harrykimpel@hotmail.com>

2023-03-16 03:46 UTC, sebsnyk requested changes

2023-03-16 03:46 UTC, sebsnyk commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +        configuration: [Debug, Release]
Is there a difference in windows solution files depending on Debug / Release files?

2023-03-16 03:46 UTC, sebsnyk commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +on:
Can we remove this, so it works on all branches and PRs

2023-03-16 03:46 UTC, sebsnyk commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +      windows-latest # For a list of available runner types, refer to
This is using a somewhat heavy windows image, but then just does `dotnet restore` and Snyk CLI, which is .NET Core. In those cases we can just use a lightweight linux image.
 WDYT

2023-03-16 03:46 UTC, sebsnyk commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +      Solution_Name: your-solution-name # Replace with your solution name, i.e. MyWpfApp.sln.
How are these variables used?

2023-03-16 03:46 UTC, sebsnyk commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +      - name: Execute unit tests
Usually, I would prefer to keep the CLI examples here very lightweight and self-contained. In this case, we don't need to run unit tests (and prepare the system for it); just to run security scans. Customers will already have actions files for those use cases in place. The snyk gh action file should be additive.

2023-03-16 03:46 UTC, sebsnyk commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +          .\snyk.exe -v
not needed

2023-03-16 03:46 UTC, sebsnyk commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +          .\snyk.exe monitor
this will not run if `test` in the line above fails?

2023-04-19 00:11 UTC, sebsnyk commented
@mcsnyk do you want to take over this one?

2023-04-20 08:50 UTC, harrykimpel commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +        configuration: [Debug, Release]
not in the solution file, but wen running the build

2023-04-20 08:59 UTC, harrykimpel commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +on:
hmmm, other examples follow the same pattern, e.g. https://github.com/harrykimpel/snyk-cicd-integration-examples/blob/da3770ecbd0bfa03bccd14216e894f8298165376/GitHub/GH%20Action%20pipeline-FullPlatform.yml#L5

2023-04-20 09:00 UTC, harrykimpel commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +      windows-latest # For a list of available runner types, refer to
that's the whole purpose to show a Windows example. sure, for dotnet core a linux image would work as well

2023-04-20 09:04 UTC, harrykimpel commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +      Solution_Name: your-solution-name # Replace with your solution name, i.e. MyWpfApp.sln.
during build process ... the example is based on a starter workflow template

2023-04-20 09:11 UTC, harrykimpel commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +      Solution_Name: your-solution-name # Replace with your solution name, i.e. MyWpfApp.sln.
removed them to keep it clean

2023-04-20 09:12 UTC, harrykimpel commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +      - name: Execute unit tests
removed

2023-04-20 09:12 UTC, harrykimpel commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +          .\snyk.exe -v
removed

2023-04-20 09:13 UTC, harrykimpel commented on GitHub/GH Action pipeline-Windows-Dotnet-CLI.yml
> +          .\snyk.exe monitor
split the test and monitor into separate steps

2024-04-02 13:33 UTC, merged